In [0]:
#import basic libraries

#data management
import numpy as np
import pandas as pd

#ML
from sklearn import linear_model

#visualisation
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
#load data
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv")
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
#import math library
import math

#get median
mb=math.floor(df.bedrooms.median())
mb

4

In [0]:
#populate nulls with median value
df.bedrooms.fillna(mb, inplace=True)

In [9]:
#display data
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [0]:
#create LinearRegression object
reg=linear_model.LinearRegression()

In [11]:
#train model with 3 variables
reg.fit(df[["area", "bedrooms", "age"]],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
#predict sample value
reg.predict([[4100,6,8]])

array([795258.55102673])

In [13]:
# check coef -> a in ax+b
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

## Second example

In [15]:
#install word2number library
!pip install word2number

Collecting word2number
  Downloading https://files.pythonhosted.org/packages/4a/29/a31940c848521f0725f0df6b25dca8917f13a2025b0e8fcbe5d0457e45e6/word2number-1.1.zip
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-cp36-none-any.whl size=5587 sha256=5b01f6e8483b72f445050da72a5d7d4a750d0bb2dd726161fe16536b8b62cd12
  Stored in directory: /root/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [0]:
#import word to number library
from word2number import w2n

In [17]:
#load data
hr = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
hr

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [18]:
#fill nulls with "zero" (string)
hr.experience.fillna("zero", inplace=True)
hr

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [0]:
#convert strings to numbers
hr.experience = hr.experience.apply(w2n.word_to_num)

In [20]:
#fill nulls with median
hr.fillna(hr["test_score(out of 10)"].median(), inplace=True)
hr

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [0]:
#create LinearRegression object
reg_hr=linear_model.LinearRegression()

In [22]:
#train model
reg.fit(hr[["experience", "test_score(out of 10)", "interview_score(out of 10)"]],hr["salary($)"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
#sample prediction
reg.predict([[2,9,6]])

array([53205.96797671])